// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../note_index.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<NoteIndexListResult> listIndexedNotes({
  required String directoryPath,
  required String kind,
}) => RustLib.instance.api.crateApiNoteIndexApiListIndexedNotes(
  directoryPath: directoryPath,
  kind: kind,
);

Future<NoteIndexRefreshResult> refreshNoteIndex({
  required String directoryPath,
  required String kind,
}) => RustLib.instance.api.crateApiNoteIndexApiRefreshNoteIndex(
  directoryPath: directoryPath,
  kind: kind,
);

Future<NoteIndexRefreshResult> indexNoteFile({
  required String directoryPath,
  required String kind,
  required String notePath,
}) => RustLib.instance.api.crateApiNoteIndexApiIndexNoteFile(
  directoryPath: directoryPath,
  kind: kind,
  notePath: notePath,
);

Future<NoteContentResult> loadNoteContent({
  required String directoryPath,
  required String notePath,
}) => RustLib.instance.api.crateApiNoteIndexApiLoadNoteContent(
  directoryPath: directoryPath,
  notePath: notePath,
);

Future<NoteSearchResult> searchIndexedNotes({
  required String directoryPath,
  required String kind,
  required String query,
}) => RustLib.instance.api.crateApiNoteIndexApiSearchIndexedNotes(
  directoryPath: directoryPath,
  kind: kind,
  query: query,
);

Future<NoteSearchResult> searchIndexedNotesByKind({
  required String directoryPath,
  required String kind,
  required List<String> queries,
  required int maxResults,
}) => RustLib.instance.api.crateApiNoteIndexApiSearchIndexedNotesByKind(
  directoryPath: directoryPath,
  kind: kind,
  queries: queries,
  maxResults: maxResults,
);

Future<NoteSearchResult> searchAllIndexedNotes({
  required String dailyDirectoryPath,
  required String weeklyDirectoryPath,
  required String monthlyDirectoryPath,
  required String diaryDirectoryPath,
  required List<String> queries,
  required int maxResults,
}) => RustLib.instance.api.crateApiNoteIndexApiSearchAllIndexedNotes(
  dailyDirectoryPath: dailyDirectoryPath,
  weeklyDirectoryPath: weeklyDirectoryPath,
  monthlyDirectoryPath: monthlyDirectoryPath,
  diaryDirectoryPath: diaryDirectoryPath,
  queries: queries,
  maxResults: maxResults,
);
