// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../ai.dart';
import '../frb_generated.dart';
import '../semantic_search.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<BigInt> indexDiaryEmbeddings({
  required String appDataDir,
  required String diaryDirectory,
  required AiProvider provider,
  required AiModel model,
}) => RustLib.instance.api.crateApiSemanticSearchApiIndexDiaryEmbeddings(
  appDataDir: appDataDir,
  diaryDirectory: diaryDirectory,
  provider: provider,
  model: model,
);

Future<List<SemanticHit>> semanticSearchDiary({
  required String appDataDir,
  required String query,
  required AiProvider provider,
  required AiModel model,
  required int topK,
}) => RustLib.instance.api.crateApiSemanticSearchApiSemanticSearchDiary(
  appDataDir: appDataDir,
  query: query,
  provider: provider,
  model: model,
  topK: topK,
);
