// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../stats.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty_snapshot`

Future<bool> recordAppStartup({required String appDataDir}) => RustLib
    .instance
    .api
    .crateApiStatsApiRecordAppStartup(appDataDir: appDataDir);

Future<bool> recordHomeGeneration({required String appDataDir}) => RustLib
    .instance
    .api
    .crateApiStatsApiRecordHomeGeneration(appDataDir: appDataDir);

Future<bool> recordWorkTime({
  required String appDataDir,
  required int workSeconds,
  required double coins,
}) => RustLib.instance.api.crateApiStatsApiRecordWorkTime(
  appDataDir: appDataDir,
  workSeconds: workSeconds,
  coins: coins,
);

Future<bool> recordDiaryEntry({
  required String appDataDir,
  required String date,
  required String mood,
}) => RustLib.instance.api.crateApiStatsApiRecordDiaryEntry(
  appDataDir: appDataDir,
  date: date,
  mood: mood,
);

Future<List<MoodEntry>> getMoodDistribution({
  required String appDataDir,
  required String startDate,
  required String endDate,
}) => RustLib.instance.api.crateApiStatsApiGetMoodDistribution(
  appDataDir: appDataDir,
  startDate: startDate,
  endDate: endDate,
);

Future<StatsSnapshot> getStatsSnapshot({
  required String appDataDir,
  required String dailyNotesDir,
  required String weeklyNotesDir,
  required String monthlyNotesDir,
  required String diaryNotesDir,
  required String startDate,
  required String endDate,
}) => RustLib.instance.api.crateApiStatsApiGetStatsSnapshot(
  appDataDir: appDataDir,
  dailyNotesDir: dailyNotesDir,
  weeklyNotesDir: weeklyNotesDir,
  monthlyNotesDir: monthlyNotesDir,
  diaryNotesDir: diaryNotesDir,
  startDate: startDate,
  endDate: endDate,
);
