// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'ai.dart';
import 'api/ai_api.dart';
import 'api/cloud_sync_api.dart';
import 'api/note_image_cleanup_api.dart';
import 'api/note_index_api.dart';
import 'api/report_api.dart';
import 'api/semantic_search_api.dart';
import 'api/stats_api.dart';
import 'cloud_sync.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'note_image_cleanup.dart';
import 'note_index.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'report_regeneration.dart';
import 'semantic_search.dart';
import 'stats.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<MemoryToolChatStreamEvent>
  dco_decode_StreamSink_memory_tool_chat_stream_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AiChatMessage dco_decode_ai_chat_message(dynamic raw);

  @protected
  AiImageAttachment dco_decode_ai_image_attachment(dynamic raw);

  @protected
  AiModel dco_decode_ai_model(dynamic raw);

  @protected
  AiProvider dco_decode_ai_provider(dynamic raw);

  @protected
  AiTextResult dco_decode_ai_text_result(dynamic raw);

  @protected
  AiToolCall dco_decode_ai_tool_call(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AiModel dco_decode_box_autoadd_ai_model(dynamic raw);

  @protected
  AiProvider dco_decode_box_autoadd_ai_provider(dynamic raw);

  @protected
  CloudSyncConfig dco_decode_box_autoadd_cloud_sync_config(dynamic raw);

  @protected
  CloudSyncNoteUploadRequest
  dco_decode_box_autoadd_cloud_sync_note_upload_request(dynamic raw);

  @protected
  CloudSyncRequest dco_decode_box_autoadd_cloud_sync_request(dynamic raw);

  @protected
  DailyMergeRequest dco_decode_box_autoadd_daily_merge_request(dynamic raw);

  @protected
  DiaryEntryRequest dco_decode_box_autoadd_diary_entry_request(dynamic raw);

  @protected
  DiaryReviewRequest dco_decode_box_autoadd_diary_review_request(dynamic raw);

  @protected
  FimCompleteRequest dco_decode_box_autoadd_fim_complete_request(dynamic raw);

  @protected
  MemoryToolChatRequest dco_decode_box_autoadd_memory_tool_chat_request(
    dynamic raw,
  );

  @protected
  RegenerateReportRequest dco_decode_box_autoadd_regenerate_report_request(
    dynamic raw,
  );

  @protected
  ReportRequest dco_decode_box_autoadd_report_request(dynamic raw);

  @protected
  StructuredNoteRequest dco_decode_box_autoadd_structured_note_request(
    dynamic raw,
  );

  @protected
  CloudSyncConfig dco_decode_cloud_sync_config(dynamic raw);

  @protected
  CloudSyncNoteUploadRequest dco_decode_cloud_sync_note_upload_request(
    dynamic raw,
  );

  @protected
  CloudSyncRequest dco_decode_cloud_sync_request(dynamic raw);

  @protected
  CloudSyncResult dco_decode_cloud_sync_result(dynamic raw);

  @protected
  DailyActivity dco_decode_daily_activity(dynamic raw);

  @protected
  DailyMergeRequest dco_decode_daily_merge_request(dynamic raw);

  @protected
  DailyTokenUsage dco_decode_daily_token_usage(dynamic raw);

  @protected
  DeleteModifyConflict dco_decode_delete_modify_conflict(dynamic raw);

  @protected
  DiaryEntryRequest dco_decode_diary_entry_request(dynamic raw);

  @protected
  DiaryEntryResult dco_decode_diary_entry_result(dynamic raw);

  @protected
  DiaryReviewRequest dco_decode_diary_review_request(dynamic raw);

  @protected
  DiaryReviewResult dco_decode_diary_review_result(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FimCompleteRequest dco_decode_fim_complete_request(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AiChatMessage> dco_decode_list_ai_chat_message(dynamic raw);

  @protected
  List<AiImageAttachment> dco_decode_list_ai_image_attachment(dynamic raw);

  @protected
  List<AiModel> dco_decode_list_ai_model(dynamic raw);

  @protected
  List<AiToolCall> dco_decode_list_ai_tool_call(dynamic raw);

  @protected
  List<DailyActivity> dco_decode_list_daily_activity(dynamic raw);

  @protected
  List<DailyTokenUsage> dco_decode_list_daily_token_usage(dynamic raw);

  @protected
  List<DeleteModifyConflict> dco_decode_list_delete_modify_conflict(
    dynamic raw,
  );

  @protected
  List<MoodEntry> dco_decode_list_mood_entry(dynamic raw);

  @protected
  List<NoteImageCleanupEntry> dco_decode_list_note_image_cleanup_entry(
    dynamic raw,
  );

  @protected
  List<NoteIndexEntry> dco_decode_list_note_index_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProviderTokenUsage> dco_decode_list_provider_token_usage(dynamic raw);

  @protected
  List<SemanticHit> dco_decode_list_semantic_hit(dynamic raw);

  @protected
  List<StructuredNoteSection> dco_decode_list_structured_note_section(
    dynamic raw,
  );

  @protected
  List<StructuredNoteSectionDefinition>
  dco_decode_list_structured_note_section_definition(dynamic raw);

  @protected
  MemoryToolChatRequest dco_decode_memory_tool_chat_request(dynamic raw);

  @protected
  MemoryToolChatResult dco_decode_memory_tool_chat_result(dynamic raw);

  @protected
  MemoryToolChatStreamEvent dco_decode_memory_tool_chat_stream_event(
    dynamic raw,
  );

  @protected
  ModelListResult dco_decode_model_list_result(dynamic raw);

  @protected
  MoodEntry dco_decode_mood_entry(dynamic raw);

  @protected
  NoteContentResult dco_decode_note_content_result(dynamic raw);

  @protected
  NoteImageCleanupDeleteResult dco_decode_note_image_cleanup_delete_result(
    dynamic raw,
  );

  @protected
  NoteImageCleanupEntry dco_decode_note_image_cleanup_entry(dynamic raw);

  @protected
  NoteImageCleanupScanResult dco_decode_note_image_cleanup_scan_result(
    dynamic raw,
  );

  @protected
  NoteIndexEntry dco_decode_note_index_entry(dynamic raw);

  @protected
  NoteIndexListResult dco_decode_note_index_list_result(dynamic raw);

  @protected
  NoteIndexRefreshResult dco_decode_note_index_refresh_result(dynamic raw);

  @protected
  NoteSearchResult dco_decode_note_search_result(dynamic raw);

  @protected
  ProviderTestResult dco_decode_provider_test_result(dynamic raw);

  @protected
  ProviderTokenUsage dco_decode_provider_token_usage(dynamic raw);

  @protected
  RegenerateReportRequest dco_decode_regenerate_report_request(dynamic raw);

  @protected
  RegenerateReportResult dco_decode_regenerate_report_result(dynamic raw);

  @protected
  ReportRequest dco_decode_report_request(dynamic raw);

  @protected
  SemanticHit dco_decode_semantic_hit(dynamic raw);

  @protected
  StatsSnapshot dco_decode_stats_snapshot(dynamic raw);

  @protected
  StatsSummary dco_decode_stats_summary(dynamic raw);

  @protected
  StructuredNoteRequest dco_decode_structured_note_request(dynamic raw);

  @protected
  StructuredNoteResult dco_decode_structured_note_result(dynamic raw);

  @protected
  StructuredNoteSection dco_decode_structured_note_section(dynamic raw);

  @protected
  StructuredNoteSectionDefinition dco_decode_structured_note_section_definition(
    dynamic raw,
  );

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<MemoryToolChatStreamEvent>
  sse_decode_StreamSink_memory_tool_chat_stream_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AiChatMessage sse_decode_ai_chat_message(SseDeserializer deserializer);

  @protected
  AiImageAttachment sse_decode_ai_image_attachment(
    SseDeserializer deserializer,
  );

  @protected
  AiModel sse_decode_ai_model(SseDeserializer deserializer);

  @protected
  AiProvider sse_decode_ai_provider(SseDeserializer deserializer);

  @protected
  AiTextResult sse_decode_ai_text_result(SseDeserializer deserializer);

  @protected
  AiToolCall sse_decode_ai_tool_call(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AiModel sse_decode_box_autoadd_ai_model(SseDeserializer deserializer);

  @protected
  AiProvider sse_decode_box_autoadd_ai_provider(SseDeserializer deserializer);

  @protected
  CloudSyncConfig sse_decode_box_autoadd_cloud_sync_config(
    SseDeserializer deserializer,
  );

  @protected
  CloudSyncNoteUploadRequest
  sse_decode_box_autoadd_cloud_sync_note_upload_request(
    SseDeserializer deserializer,
  );

  @protected
  CloudSyncRequest sse_decode_box_autoadd_cloud_sync_request(
    SseDeserializer deserializer,
  );

  @protected
  DailyMergeRequest sse_decode_box_autoadd_daily_merge_request(
    SseDeserializer deserializer,
  );

  @protected
  DiaryEntryRequest sse_decode_box_autoadd_diary_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  DiaryReviewRequest sse_decode_box_autoadd_diary_review_request(
    SseDeserializer deserializer,
  );

  @protected
  FimCompleteRequest sse_decode_box_autoadd_fim_complete_request(
    SseDeserializer deserializer,
  );

  @protected
  MemoryToolChatRequest sse_decode_box_autoadd_memory_tool_chat_request(
    SseDeserializer deserializer,
  );

  @protected
  RegenerateReportRequest sse_decode_box_autoadd_regenerate_report_request(
    SseDeserializer deserializer,
  );

  @protected
  ReportRequest sse_decode_box_autoadd_report_request(
    SseDeserializer deserializer,
  );

  @protected
  StructuredNoteRequest sse_decode_box_autoadd_structured_note_request(
    SseDeserializer deserializer,
  );

  @protected
  CloudSyncConfig sse_decode_cloud_sync_config(SseDeserializer deserializer);

  @protected
  CloudSyncNoteUploadRequest sse_decode_cloud_sync_note_upload_request(
    SseDeserializer deserializer,
  );

  @protected
  CloudSyncRequest sse_decode_cloud_sync_request(SseDeserializer deserializer);

  @protected
  CloudSyncResult sse_decode_cloud_sync_result(SseDeserializer deserializer);

  @protected
  DailyActivity sse_decode_daily_activity(SseDeserializer deserializer);

  @protected
  DailyMergeRequest sse_decode_daily_merge_request(
    SseDeserializer deserializer,
  );

  @protected
  DailyTokenUsage sse_decode_daily_token_usage(SseDeserializer deserializer);

  @protected
  DeleteModifyConflict sse_decode_delete_modify_conflict(
    SseDeserializer deserializer,
  );

  @protected
  DiaryEntryRequest sse_decode_diary_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  DiaryEntryResult sse_decode_diary_entry_result(SseDeserializer deserializer);

  @protected
  DiaryReviewRequest sse_decode_diary_review_request(
    SseDeserializer deserializer,
  );

  @protected
  DiaryReviewResult sse_decode_diary_review_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FimCompleteRequest sse_decode_fim_complete_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AiChatMessage> sse_decode_list_ai_chat_message(
    SseDeserializer deserializer,
  );

  @protected
  List<AiImageAttachment> sse_decode_list_ai_image_attachment(
    SseDeserializer deserializer,
  );

  @protected
  List<AiModel> sse_decode_list_ai_model(SseDeserializer deserializer);

  @protected
  List<AiToolCall> sse_decode_list_ai_tool_call(SseDeserializer deserializer);

  @protected
  List<DailyActivity> sse_decode_list_daily_activity(
    SseDeserializer deserializer,
  );

  @protected
  List<DailyTokenUsage> sse_decode_list_daily_token_usage(
    SseDeserializer deserializer,
  );

  @protected
  List<DeleteModifyConflict> sse_decode_list_delete_modify_conflict(
    SseDeserializer deserializer,
  );

  @protected
  List<MoodEntry> sse_decode_list_mood_entry(SseDeserializer deserializer);

  @protected
  List<NoteImageCleanupEntry> sse_decode_list_note_image_cleanup_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<NoteIndexEntry> sse_decode_list_note_index_entry(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProviderTokenUsage> sse_decode_list_provider_token_usage(
    SseDeserializer deserializer,
  );

  @protected
  List<SemanticHit> sse_decode_list_semantic_hit(SseDeserializer deserializer);

  @protected
  List<StructuredNoteSection> sse_decode_list_structured_note_section(
    SseDeserializer deserializer,
  );

  @protected
  List<StructuredNoteSectionDefinition>
  sse_decode_list_structured_note_section_definition(
    SseDeserializer deserializer,
  );

  @protected
  MemoryToolChatRequest sse_decode_memory_tool_chat_request(
    SseDeserializer deserializer,
  );

  @protected
  MemoryToolChatResult sse_decode_memory_tool_chat_result(
    SseDeserializer deserializer,
  );

  @protected
  MemoryToolChatStreamEvent sse_decode_memory_tool_chat_stream_event(
    SseDeserializer deserializer,
  );

  @protected
  ModelListResult sse_decode_model_list_result(SseDeserializer deserializer);

  @protected
  MoodEntry sse_decode_mood_entry(SseDeserializer deserializer);

  @protected
  NoteContentResult sse_decode_note_content_result(
    SseDeserializer deserializer,
  );

  @protected
  NoteImageCleanupDeleteResult sse_decode_note_image_cleanup_delete_result(
    SseDeserializer deserializer,
  );

  @protected
  NoteImageCleanupEntry sse_decode_note_image_cleanup_entry(
    SseDeserializer deserializer,
  );

  @protected
  NoteImageCleanupScanResult sse_decode_note_image_cleanup_scan_result(
    SseDeserializer deserializer,
  );

  @protected
  NoteIndexEntry sse_decode_note_index_entry(SseDeserializer deserializer);

  @protected
  NoteIndexListResult sse_decode_note_index_list_result(
    SseDeserializer deserializer,
  );

  @protected
  NoteIndexRefreshResult sse_decode_note_index_refresh_result(
    SseDeserializer deserializer,
  );

  @protected
  NoteSearchResult sse_decode_note_search_result(SseDeserializer deserializer);

  @protected
  ProviderTestResult sse_decode_provider_test_result(
    SseDeserializer deserializer,
  );

  @protected
  ProviderTokenUsage sse_decode_provider_token_usage(
    SseDeserializer deserializer,
  );

  @protected
  RegenerateReportRequest sse_decode_regenerate_report_request(
    SseDeserializer deserializer,
  );

  @protected
  RegenerateReportResult sse_decode_regenerate_report_result(
    SseDeserializer deserializer,
  );

  @protected
  ReportRequest sse_decode_report_request(SseDeserializer deserializer);

  @protected
  SemanticHit sse_decode_semantic_hit(SseDeserializer deserializer);

  @protected
  StatsSnapshot sse_decode_stats_snapshot(SseDeserializer deserializer);

  @protected
  StatsSummary sse_decode_stats_summary(SseDeserializer deserializer);

  @protected
  StructuredNoteRequest sse_decode_structured_note_request(
    SseDeserializer deserializer,
  );

  @protected
  StructuredNoteResult sse_decode_structured_note_result(
    SseDeserializer deserializer,
  );

  @protected
  StructuredNoteSection sse_decode_structured_note_section(
    SseDeserializer deserializer,
  );

  @protected
  StructuredNoteSectionDefinition sse_decode_structured_note_section_definition(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_memory_tool_chat_stream_event_Sse(
    RustStreamSink<MemoryToolChatStreamEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_ai_chat_message(AiChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_ai_image_attachment(
    AiImageAttachment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_model(AiModel self, SseSerializer serializer);

  @protected
  void sse_encode_ai_provider(AiProvider self, SseSerializer serializer);

  @protected
  void sse_encode_ai_text_result(AiTextResult self, SseSerializer serializer);

  @protected
  void sse_encode_ai_tool_call(AiToolCall self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_model(AiModel self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ai_provider(
    AiProvider self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cloud_sync_config(
    CloudSyncConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cloud_sync_note_upload_request(
    CloudSyncNoteUploadRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cloud_sync_request(
    CloudSyncRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_daily_merge_request(
    DailyMergeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_diary_entry_request(
    DiaryEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_diary_review_request(
    DiaryReviewRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_fim_complete_request(
    FimCompleteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_memory_tool_chat_request(
    MemoryToolChatRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_regenerate_report_request(
    RegenerateReportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_report_request(
    ReportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_structured_note_request(
    StructuredNoteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_sync_config(
    CloudSyncConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_sync_note_upload_request(
    CloudSyncNoteUploadRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_sync_request(
    CloudSyncRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cloud_sync_result(
    CloudSyncResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_daily_activity(DailyActivity self, SseSerializer serializer);

  @protected
  void sse_encode_daily_merge_request(
    DailyMergeRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_daily_token_usage(
    DailyTokenUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delete_modify_conflict(
    DeleteModifyConflict self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diary_entry_request(
    DiaryEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diary_entry_result(
    DiaryEntryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diary_review_request(
    DiaryReviewRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_diary_review_result(
    DiaryReviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_fim_complete_request(
    FimCompleteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_chat_message(
    List<AiChatMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_image_attachment(
    List<AiImageAttachment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ai_model(List<AiModel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ai_tool_call(
    List<AiToolCall> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_daily_activity(
    List<DailyActivity> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_daily_token_usage(
    List<DailyTokenUsage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_delete_modify_conflict(
    List<DeleteModifyConflict> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mood_entry(
    List<MoodEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_image_cleanup_entry(
    List<NoteImageCleanupEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_index_entry(
    List<NoteIndexEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_token_usage(
    List<ProviderTokenUsage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_semantic_hit(
    List<SemanticHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_structured_note_section(
    List<StructuredNoteSection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_structured_note_section_definition(
    List<StructuredNoteSectionDefinition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_tool_chat_request(
    MemoryToolChatRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_tool_chat_result(
    MemoryToolChatResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_tool_chat_stream_event(
    MemoryToolChatStreamEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_model_list_result(
    ModelListResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mood_entry(MoodEntry self, SseSerializer serializer);

  @protected
  void sse_encode_note_content_result(
    NoteContentResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_image_cleanup_delete_result(
    NoteImageCleanupDeleteResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_image_cleanup_entry(
    NoteImageCleanupEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_image_cleanup_scan_result(
    NoteImageCleanupScanResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_index_entry(
    NoteIndexEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_index_list_result(
    NoteIndexListResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_index_refresh_result(
    NoteIndexRefreshResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_search_result(
    NoteSearchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_test_result(
    ProviderTestResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_token_usage(
    ProviderTokenUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_regenerate_report_request(
    RegenerateReportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_regenerate_report_result(
    RegenerateReportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_report_request(ReportRequest self, SseSerializer serializer);

  @protected
  void sse_encode_semantic_hit(SemanticHit self, SseSerializer serializer);

  @protected
  void sse_encode_stats_snapshot(StatsSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_stats_summary(StatsSummary self, SseSerializer serializer);

  @protected
  void sse_encode_structured_note_request(
    StructuredNoteRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_structured_note_result(
    StructuredNoteResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_structured_note_section(
    StructuredNoteSection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_structured_note_section_definition(
    StructuredNoteSectionDefinition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
